spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: admin
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true